# Generated by Django 4.0.2 on 2022-09-12 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(max_length=50)),
                ('line2', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Governorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Governorate_Name', models.CharField(max_length=30)),
                ('zipCode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OpeningHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_from', models.TimeField(auto_now_add=True)),
                ('open_to', models.TimeField(auto_now_add=True)),
                ('from_Day', models.CharField(max_length=10)),
                ('to_Day', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Place_Name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=800, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.address')),
                ('openingHours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.openinghour')),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(max_length=100, null=True)),
                ('instagram', models.CharField(max_length=100, null=True)),
                ('twitter', models.CharField(max_length=100, null=True)),
                ('website', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ATM',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='page.place')),
            ],
            bases=('page.place',),
        ),
        migrations.CreateModel(
            name='Backers',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='page.place')),
            ],
            bases=('page.place',),
        ),
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='page.place')),
            ],
            bases=('page.place',),
        ),
        migrations.CreateModel(
            name='CarRepair',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='page.place')),
                ('products', models.TextField(max_length=200)),
                ('brands', models.CharField(max_length=40)),
            ],
            bases=('page.place',),
        ),
        migrations.CreateModel(
            name='GroceryStore',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='page.place')),
                ('brands', models.CharField(max_length=40)),
            ],
            bases=('page.place',),
        ),
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='page.place')),
            ],
            bases=('page.place',),
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='page.place')),
            ],
            bases=('page.place',),
        ),
        migrations.CreateModel(
            name='MedicalClinic',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='page.place')),
                ('products', models.TextField(max_length=200)),
                ('brands', models.CharField(max_length=40)),
            ],
            bases=('page.place',),
        ),
        migrations.CreateModel(
            name='PlayGrounds',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='page.place')),
            ],
            bases=('page.place',),
        ),
        migrations.CreateModel(
            name='Resturant',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='page.place')),
                ('dishes', models.CharField(max_length=100, null=True)),
                ('atmosphere', models.CharField(max_length=30, null=True)),
            ],
            bases=('page.place',),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(max_length=1000, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.place')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('stars', models.IntegerField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.place')),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='social',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.social'),
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.place')),
            ],
        ),
        migrations.CreateModel(
            name='ImageCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='image')),
                ('is_default', models.BooleanField(default=False)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.place')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City_name', models.CharField(max_length=30, null=True)),
                ('governorate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='page.governorate')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='page.city'),
        ),
    ]
