# Generated by Django 3.2 on 2022-09-06 09:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(max_length=30)),
                ('line2', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Governorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('zipCode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OpeningHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openfrom', models.TimeField()),
                ('opento', models.TimeField()),
                ('fromDay', models.CharField(max_length=10)),
                ('toDay', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('phone1', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('phone2', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=800)),
                ('cover', models.ImageField(upload_to='')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.address')),
                ('openingHours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.openinghour')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.phone')),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(max_length=100)),
                ('instagram', models.CharField(max_length=100)),
                ('twitter', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CarRepair',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='page.place')),
                ('products', models.TextField(max_length=200)),
                ('brands', models.CharField(max_length=40)),
            ],
            bases=('page.place',),
        ),
        migrations.CreateModel(
            name='GroceryStore',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='page.place')),
                ('brands', models.CharField(max_length=40)),
            ],
            bases=('page.place',),
        ),
        migrations.CreateModel(
            name='MedicalClinic',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='page.place')),
                ('products', models.TextField(max_length=200)),
                ('brands', models.CharField(max_length=40)),
            ],
            bases=('page.place',),
        ),
        migrations.CreateModel(
            name='Resturant',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='page.place')),
                ('dishes', models.CharField(max_length=100)),
                ('atmosphere', models.CharField(max_length=30)),
            ],
            bases=('page.place',),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.place')),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('ratedTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.place')),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='social',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.social'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.place')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('governorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.governorate')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.city'),
        ),
    ]
