# Generated by Django 4.0.2 on 2022-09-12 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='page.city'),
        ),
        migrations.AlterField(
            model_name='city',
            name='governorate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='page.governorate'),
        ),
        migrations.AlterField(
            model_name='imagecollection',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='page.place'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='page.place'),
        ),
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='page.address'),
        ),
        migrations.AlterField(
            model_name='place',
            name='openingHours',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='page.openinghour'),
        ),
        migrations.AlterField(
            model_name='place',
            name='social',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='page.social'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='page.place'),
        ),
        migrations.AlterField(
            model_name='review',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='page.place'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
