# Generated by Django 2.2.28 on 2022-09-14 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='address',
        ),
        migrations.AddField(
            model_name='place',
            name='address',
            field=models.ManyToManyField(to='page.Address'),
        ),
    ]
