# Generated by Django 2.2.28 on 2022-09-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecollection',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
