# Generated by Django 4.0.2 on 2022-09-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='cover',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
