# Generated by Django 3.2 on 2022-09-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_alter_address_city_alter_city_governorate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
