# Generated by Django 4.0.2 on 2022-09-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_alter_imagecollection_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecollection',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='media/', verbose_name='Image'),
        ),
    ]
