# Generated by Django 4.0.2 on 2022-09-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_alter_imagecollection_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecollection',
            name='image',
            field=models.ImageField(blank=True, default='places/default.jpg', null=True, upload_to='media/places/', verbose_name='Image'),
        ),
    ]
