# Generated by Django 4.0.2 on 2022-09-08 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_rename_name_place_place_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='openinghour',
            old_name='fromDay',
            new_name='from_Day',
        ),
        migrations.RenameField(
            model_name='openinghour',
            old_name='openfrom',
            new_name='open_from',
        ),
        migrations.RenameField(
            model_name='openinghour',
            old_name='opento',
            new_name='open_to',
        ),
        migrations.RenameField(
            model_name='openinghour',
            old_name='toDay',
            new_name='to_Day',
        ),
    ]
