# Generated by Django 4.0.2 on 2022-09-08 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_rename_fromday_openinghour_from_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resturant',
            name='atmosphere',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='resturant',
            name='dishes',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
