# Generated by Django 4.0.2 on 2022-09-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_alter_imagecollection_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecollection',
            name='image',
            field=models.FileField(blank=True, default='IMG.jpg', null=True, upload_to='places/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='imagecollection',
            name='is_default',
            field=models.BooleanField(default=True),
        ),
    ]
