# Generated by Django 4.0.2 on 2022-09-23 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_alter_imagecollection_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecollection',
            name='image',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to='places/'),
        ),
        migrations.AlterField(
            model_name='imagecollection',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
