# Generated by Django 4.0.2 on 2022-09-09 00:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='photosCollection',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(blank=True, upload_to=''), size=10), null=True, size=10),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
