# Generated by Django 4.0.2 on 2022-09-23 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0010_alter_imagecollection_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecollection',
            name='image',
            field=models.ImageField(upload_to='places/'),
        ),
        migrations.AlterField(
            model_name='imagecollection',
            name='is_default',
            field=models.BooleanField(default=True),
        ),
    ]
