# Generated by Django 4.0.2 on 2022-09-25 09:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0017_alter_imagecollection_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecollection',
            name='image',
            field=models.ImageField(null=True, upload_to='places/', validators=[django.core.validators.FileExtensionValidator(['jpg'])]),
        ),
    ]
