# Generated by Django 4.0.2 on 2022-09-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0022_rename_addimages_place_add_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='add_images',
            field=models.ImageField(null=True, upload_to='places/'),
        ),
    ]
