# Generated by Django 4.0.2 on 2022-09-25 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0023_alter_place_add_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='add_images',
            new_name='add_image_collection',
        ),
    ]
