# Generated by Django 4.0.2 on 2022-09-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0024_rename_add_images_place_add_image_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='add_image_collection',
        ),
        migrations.AddField(
            model_name='imagecollection',
            name='add_image_collection',
            field=models.ImageField(null=True, upload_to='places/'),
        ),
    ]
