# Generated by Django 4.0.2 on 2022-09-26 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0025_remove_place_add_image_collection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagecollection',
            name='add_image_collection',
        ),
    ]
