# Generated by Django 4.0.2 on 2022-09-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0027_alter_imagecollection_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagecollection',
            name='url',
            field=models.TextField(default='image', max_length=500),
        ),
    ]
