# Generated by Django 4.0.2 on 2022-09-26 15:32

from django.db import migrations, models
import upload_validator


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0028_imagecollection_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagecollection',
            name='url',
        ),
        migrations.AlterField(
            model_name='imagecollection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='places/', validators=[upload_validator.FileTypeValidator(allowed_types=['image/jpeg', 'image/png'])]),
        ),
    ]
