# Generated by Django 4.0.2 on 2022-09-26 20:17

import any_imagefield.models.fields
from django.db import migrations
import upload_validator


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0030_alter_imagecollection_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecollection',
            name='image',
            field=any_imagefield.models.fields.AnyImageField(blank=True, default='default.jpg', null=True, upload_to='places/', validators=[upload_validator.FileTypeValidator(allowed_types=['image/jpeg', 'image/png'])]),
        ),
    ]
