# Generated by Django 4.0.2 on 2022-09-26 22:36

from django.db import migrations, models
import upload_validator


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0033_alter_imagecollection_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecollection',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='places/', validators=[upload_validator.FileTypeValidator(allowed_types=['image/jpeg', 'image/png'])]),
        ),
    ]
