# Generated by Django 4.0.2 on 2022-09-27 08:16

from django.db import migrations, models
import upload_validator


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0034_alter_imagecollection_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagecollection',
            name='is_default',
        ),
        migrations.AlterField(
            model_name='imagecollection',
            name='image',
            field=models.FileField(blank=True, default='default.jpg', null=True, upload_to='places/', validators=[upload_validator.FileTypeValidator]),
        ),
    ]
