# Generated by Django 4.0.2 on 2022-09-27 08:29

from django.db import migrations, models
import upload_validator


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0035_remove_imagecollection_is_default_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecollection',
            name='image',
            field=models.FileField(blank=True, default='default.jpg', null=True, upload_to='places/', validators=[upload_validator.FileTypeValidator(allowed_types=['image/jpeg', 'image/png'])]),
        ),
    ]
