# Generated by Django 4.0.2 on 2022-09-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0036_alter_imagecollection_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='image_url',
            field=models.SlugField(default='image.jpg'),
        ),
    ]
