# Generated by Django 4.0.2 on 2022-09-27 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0037_place_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='image_url',
        ),
    ]
