# Generated by Django 4.0.2 on 2022-09-27 15:32

from django.db import migrations, models
import upload_validator


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0038_remove_place_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecollection',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', max_length=254, null=True, upload_to='places/', validators=[upload_validator.FileTypeValidator(allowed_types=['image/jpeg', 'image/png'])]),
        ),
    ]
