# Generated by Django 3.2 on 2022-09-07 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('authtoken', '0003_tokenproxy'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlaceOwner',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
